version: 5
daemon:
  log_level: info
  admin_group: wheel
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:731F-1682:5701-0000:03:00.0:
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 0.5
      temperature_key: edge
      interval_ms: 500
      curve:
        40: 0.3
        50: 0.35
        60: 0.5
        70: 0.75
        80: 1.0
      spindown_delay_ms: 5000
      change_threshold: 2
    power_cap: 160.0
    performance_level: manual
    max_core_clock: 1905
    max_memory_clock: 875
    max_voltage: 1000
    power_profile_mode_index: 0
    power_states:
      memory_clock:
      - 0
      - 1
      - 2
      - 3
      core_clock:
      - 0
      - 1
      - 2
profiles:
  Altered:
    gpus:
      1002:731F-1682:5701-0000:03:00.0:
        fan_control_enabled: true
        fan_control_settings:
          mode: curve
          static_speed: 0.5
          temperature_key: edge
          interval_ms: 500
          curve:
            40: 0.3
            50: 0.35
            60: 0.5
            70: 0.75
            80: 1.0
          spindown_delay_ms: 5000
          change_threshold: 2
        power_cap: 210.0
        performance_level: manual
        max_core_clock: 1905
        max_memory_clock: 875
        max_voltage: 1000
        power_profile_mode_index: 1
        power_states:
          memory_clock:
          - 1
          - 2
          - 3
          core_clock:
          - 1
          - 2
current_profile: Altered
auto_switch_profiles: false
